### ISSUE TITLE
meta: Add mkdocs static site generation

### ISSUE THREAD

**Issue by tbobm** [open-subjects/open-subjects#10]
Add mkdocs (material) support to publish open-subjects as a static site to https://subjects.tbobm.tech/.

- [x] Implement mkdocs
- [ ] Add mkdocs CI
  - [x] Generate static website
  - [x] Upload to gh pages
  - [x] Restrict to relevant files
  - [x] Restrict to commits to main
